# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbportefolje
team: oppfolging
replicas:
  min: 3
  max: 3
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
leaderElection: true
healthcheck:
  liveness:
    path: veilarbportefolje/internal/isAlive
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbportefolje/internal/isReady
    initialDay: 60
    timeout: 10
prometheus:
  enabled: true
  path: veilarbportefolje/internal/metrics
resources:
  limits:
    cpu: 6
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 2Gi
fasitResources:
  used:
  - alias: veilarbelastic_user
    resourceType: credential
    propertyMap:
      username: VEILARBELASTIC_USERNAME
      password: VEILARBELASTIC_PASSWORD
  - alias: loadbalancer:veilarbportefolje
    resourceType: loadbalancerconfig
  - alias: veilarbportefoljeDB
    resourceType: datasource
  - alias: srvveilarbportefolje
    resourceType: credential
  - alias: veilarbportefolje.filmottak.sftp.login
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: veilarbportefolje.properties
    resourceType: applicationproperties

  - alias: securityTokenService
    resourceType: baseUrl
  - alias: abac.pdp.endpoint
    resourceType: restservice
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: virksomhet:DigitalKontakinformasjon_v1
    resourceType: webserviceendpoint
  - alias: virksomhet:Enhet_v1
    resourceType: webserviceendpoint

  - alias: veilarbportefolje.solr.brukercore
    resourceType: restservice
  - alias: veilArbOppfolgingAPI
    resourceType: restservice
  - alias: veilArbAktivitetAPI
    resourceType: restservice
  - alias: veilarbdialogAPI
    resourceType: restservice
  - alias: veilarbveilederAPI
    resourceType: restservice
  - alias: unleash-api
    resourceType: restservice

  # ISSO
  - alias: isso-host
    resourceType: baseurl
  - alias: isso-jwks
    resourceType: baseurl
  - alias: isso-issuer
    resourceType: baseurl
  - alias: isso.isalive
    resourceType: baseurl
  - alias: isso-rp-user
    resourceType: credential
  - alias: veilarblogin.redirect-url
    resourceType: restservice

  exposed:
  - alias: veilArbPortefoljeAPI
    resourceType: restservice
    path: /veilarbportefolje/api

alertProfiles:
  - common-java-modules
